[manager]
sort_by = "natural"
sort_reverse = false
show_hidden = true

[opener]
text = [
	{ exec = 'micro "$@"', block = true },
]

[open]
rules = [
	{ mime = "application/*", use = "text" },
	{ mime = "text/*", use = "text" },
]
